7.1.2

diff --git a/.github/workflows/cl-testing.yml b/.github/workflows/cl-testing.yml
--- a/.github/workflows/cl-testing.yml
+++ b/.github/workflows/cl-testing.yml
@@ -113,7 +113,7 @@ jobs:
             # Check if the PM2 process is running
             if pm2 show your-service-name > /dev/null; then
               echo "Application is running. Restarting..."
-              pm2 restart "API_Test"
+              pm2 restart "API_Test" && echo "Restart successful" || echo "Restart failed"
             else
               echo "Application is not running. Starting..."
               pm2 start build/server.js --name "API_Test"
